name: "Flutter app builder"
on: push
jobs:
  build:
    name: Build apk and release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1 
      with:
        java-version: '12.x'

    - name: install dependencies
      uses: Rishabh510/Flutter-app-builder-action@master
      with:
        args: pub get

    - name: clean build
      uses: Rishabh510/Flutter-app-builder-action@master
      with:
        args: clean
        
    - name: run tests
      uses: Rishabh510/Flutter-app-builder-action@master
      with:
        args: test

#     - name: build apk
#       uses: Rishabh510/Flutter-app-builder-action@master
#       with:
#         args: build apk --debug --split-per-abi
#         args: build apk --release

    - name: build apk
      uses: steebchen/flutter@v1.0.0
      with:
        args: run

